# Generated by Django 5.2.5 on 2025-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_group_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
