# Generated by Django 5.2.8 on 2025-11-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_groupmessage_file_groupmessage_file_name_and_more'),
        ('chatapp', '0007_projectfile'),
    ]

    operations = [
    ]
